#!/usr/bin/env python3
"""
This module uses an asynchronous comprehension to collect values from an
asynchronous generator defined in another module. It showcases how to use
dynamic importing with __import__ for the async_generator function.
"""

from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronously collects ten random numbers generated by 'async_generator'.
    This is achieved using an asynchronous comprehension
    to build a list of these
    numbers and then returns the list.
    """
    return [num async for num in async_generator()]
